version: '3.7'

services:

  tailwind-vue:
    container_name: tailwind-vue
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
